select * from ubigeo;
select * from personas;
select * from entidad;
select * from expediente;
select * from variable;
select * from sigla_entidad;


/*1.MOSTRAR LA NOMENCLATURA, EL TIPO QUE PERTENECE A ESE PROCEDIMIENTO, Y EL NUMERO DE EXPEDIENTE
ADEMAS ORDENAR POR EXPEDIENTE*/
SELECT C_NOMETS,
    CASE C_TIPSEL
       WHEN 271 THEN 'ADJUDICACION SIMPLIFICADA'
       WHEN 82 THEN 'LICITACION PUBLICA'
       WHEN 75 THEN 'CONCURSO PUBLICO'
       WHEN 511 THEN 'PROCEDIMIENTO ESPECIAL'
       WHEN 84 THEN 'REGIMEN ESPECIAL'
       WHEN 384 THEN 'SUBASTA INVERSA ELECTRONICA'
       WHEN 293 THEN 'CONTRATACION DIRECTA'
       WHEN 80 THEN 'CONVENIO'
       WHEN 386 THEN 'COMPARACION DE PRECIOS'
    ELSE  'OTROS' END TIPOS, N_ID_EXPEDE
FROM EXPEDIENTE
ORDER BY 3;

/*2.REALIZAR UNA CONSULTA DE LOS EXPEDIENTES CREADOS EN EL MES DE JUNIO DEL AÑO 2019 
ADEMAS ORDENAR ASCENDENTEMENTE POR VALOR REFERENCIAL*/
SELECT E.*
FROM SYSTEM.EXPEDIENTE E
    WHERE TO_CHAR(E.D_FECCRE,'MM') = 02
    ORDER BY 13 ASC;

/*3.REALIZAR UNA CONSULTA DE LOS EXPEDIENTES CREADOS EN EL I Y II TRIMESTRE DEL 2019, ADEMAS QUE EL MONTO SEA MAYOR A 8 UITS*/
SELECT TO_CHAR(E.D_FECCRE,'MM') MESEXPEDIENTE, E.*
FROM SYSTEM.EXPEDIENTE E
WHERE 
   (TO_CHAR(E.D_FECCRE,'MM') = 01 OR TO_CHAR(E.D_FECCRE,'MM') = 03 OR 
    TO_CHAR(E.D_FECCRE,'MM') = 02 OR TO_CHAR(E.D_FECCRE,'MM') = 04 OR
    TO_CHAR(E.D_FECCRE,'MM') = 05 OR TO_CHAR(E.D_FECCRE,'MM') = 06 )AND
    C_VALRET > 30*4200
ORDER BY 2 ASC;

/*4.MODIFICAR REGISTRO*/
UPDATE SYSTEM.PERSONAS
SET C_APELL = 'ATO MARTINEZ',
    C_NOMBRE = 'LUIS ALBERTO'
WHERE C_DNI=9389098;

/*5.REALIZAR UNA CONSULTA DE LAS SIGLAS CREADAS EN EL AÑO 2017 Y QUE COMIENCEN CON LA LETRA B*/
SELECT  S.*
FROM SYSTEM.SIGLA_ENTIDAD S
WHERE TO_CHAR(S.D_FECCRE,'YY') = 17 AND C_SIGLA LIKE 'B%'
ORDER BY 1 ASC;

/*6.REALIZAR LA CONSULTA DE CORREOS DEL PERSONAL CON DOMINIO @GMAIL.COM Y QUE SU NUMERO DE DNI ACABE EN 0*/
SELECT  P.*
FROM SYSTEM.PERSONAS P
WHERE C_EMAIL LIKE '%@gmail.com' AND P.C_DNI LIKE '%0'
ORDER BY 1 ASC;

/*7.REALIZAR LA CONSULTA DE LAS ENTIDADES QUE SON MINISTERIOS, MOSTRAR EN ORDEN POR FECHA DE CREACION*/
SELECT E.*
FROM SYSTEM.ENTIDAD E
WHERE C_NOMORG LIKE 'MINISTERIO%'
ORDER BY E.D_FECACC ASC;

/*8.REALIZAR LA CONSULTA DE EXPEDIENTES EN SU PRIMERA VERSION, Y QUE SU NOMENCLATURA COMIENCE CON AS O PEC
ADEMAS QUE EL CARGO DEL FUNCIONARIO SEA ALISTA.*/
SELECT E.*
FROM SYSTEM.EXPEDIENTE E
WHERE E.N_VERSION = 1 AND (E.C_NOMETS LIKE 'AS%' OR E.C_NOMETS LIKE 'PEC%' )
    AND C_CARFUN ='ANALISTA';
    
/*9. PARA LOS VACIOS EN LA FECHA DE APROBACION DEL EXPEDIENTE, CREAR UNA COLUMNA QUE FUE CREADA POR EL SISTEMA
CASO CONTRARIO CREADA POR USUARIO*/
SELECT N_ID_EXPEDE EXPEDIENTE, NVL2(D_FECAEX, 'SISTEMA', 'USUARIO') "CREADO POR", C_NOMETS NOMENCLATURA 
FROM EXPEDIENTE;

/*MOSTRAR POR TIPO DE OBJETO DEL EXPEDIENTE Y ORDENAR POR EXPEDIENTE*/
SELECT C_NOMETS,
  CASE C_TIPOBJ
   WHEN 62 THEN 'BIEN'
   WHEN 63 THEN 'CONSULTORIA DE OBRA'
   WHEN 64 THEN 'OBRA'
  ELSE  'SERVICIO'
  END C_NOMETS, N_ID_EXPEDE
  FROM EXPEDIENTE
  ORDER BY 3;
